### ISSUE TITLE
Error: gpg failed to sign the data

### ISSUE THREAD

**Issue by alalag1** [qcastel/github-actions-maven-release#17]
### behavior
I got this error many times:

Error: 0,517 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M1:prepare (default-cli) on project commons-parent: Unable to commit files
Error: 0,517 [ERROR] Provider message:
Error: 0,517 [ERROR] The git-commit command failed.
Error: 0,517 [ERROR] Command output:
Error: 0,517 [ERROR] error: gpg failed to sign the data
Error: 0,517 [ERROR] fatal: failed to write commit object

### settings

```yaml
with:
    release-branch-name: main
    git-release-bot-name: ***
    git-release-bot-email: xxx@xxx.com
    maven-repo-server-id: ***
    maven-repo-server-username: ***
    maven-repo-server-password: ***
    ssh-private-key: ***
    gpg-enabled: true
    gpg-key-id: ***
    gpg-key: ***
    gpg-passphrase: ***
    maven-args: -Dmaven.javadoc.skip=true
    skip-perform: true
    maven-project-folder: ./
    version-major: false
    version-minor: false
    m2-home-folder: /root/.m2
  env:
    JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
```
