### ISSUE TITLE
release-branch-name is skipping

### ISSUE THREAD

**Issue by mcahuet** [qcastel/github-actions-maven-release#20]
I was trying to test this action with configurations : 

```
- name: Maven release
        uses: qcastel/github-actions-maven-release@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          version-minor: true
          release-branch-name: "main"
          skip-perform: true
```

But when it runs I get:

> Run Maven release
[Docker publish/push]   ☁  git clone 'https://github.com/qcastel/github-actions-maven-release' # ref=master
[Docker publish/push]   🐳  docker build -t act-qcastel-github-actions-maven-release-master:latest 
[Docker publish/push]   🐳  docker run image=act-qcastel-github-actions-maven-release-master:latest entrypoint=[] cmd=["release-github-actions.sh"]
| Last ${{ inputs.git-release-bot-name }} commit:
| Current commit: <myLastCommit>
| Current branch: main
| Skipping for main branch
Success - Maven release

It seems that the branch is skipped without taking into account the `release-branch-name` parameter.

In the `pom.xml` I put the following scm configuration : 
```
    <scm>
        <connection>scm:git:ssh://git@github.com::<my_repo>.git</connection>
        <developerConnection>sscm:git:ssh://git@github.com:<my_repo>.git</developerConnection>
    </scm>
```
