### ISSUE TITLE
Question on GitHub Status Checks

### ISSUE THREAD

**Issue by jayfray12** [qcastel/github-actions-maven-release#32]
I have set my `master` branch to have a branch protection rule which requires a status check to pass before merging.  When I run the release plugin I get the following:
```
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: error: GH006: Protected branch update failed for refs/heads/master.        
[ERROR] remote: error: Required status check "build" is expected.    
```
Any thoughts on how to get around this?

**Comment by qcastel** [comment]
@jayfray12 Actually a friend of mine @benjefferies did a github actions for this. You can look at what he did: https://github.com/benjefferies/branch-protection-bot

I guess you can do something similar for your situation

**Comment by jayfray12** [comment]
That looks great and may come in handy but I don't have the `Include administrators` checked.  I just have the following:
![image](https://user-images.githubusercontent.com/38667521/116136994-08a66480-a6a1-11eb-8767-bc934a7e2e6f.png)

I can run the maven release just fine on my local desktop but when I try to use the Git Action I get that error.  I've created a Personal Access Token and passed that as the `access-token` but still get the error (this is a private repo of my own)

**Comment by qcastel** [comment]
What we did in the past, in this exact situation, is we created a bot github account which is admin in the repository.
You then configure this github actions to use the credentials of the bot.

This will allow you to bypass the branch protection.

Now, you may be an admin yourself and therefore you want to enforce the rules even for you (which was our scenario). That's where the github actions of Ben becomes handy: you can disable the enforcement for admin temporarly to allow the admin bot to merge.

I think you manage to do it locally because you are an admin yourself and 'Include administrators'  is unchecked for your repo.

Fancy give it a try?

**Comment by jayfray12** [comment]
I can certainly create a bot but what is the difference of using a bot vs using my personal access token?  If I am admin and so is the bot then It should be the same thing right?

**Comment by jayfray12** [comment]
I've already followed you instructions to use the SSH key and have added the `ssh-private-key` but still get the issue :(

**Comment by qcastel** [comment]
I managed to reproduce the issue on the sample repository and to then fix. For that, I had to make a few changes:

- First, I couldnt make the bot admin to a repo inside my personal account repos. Annoying and sad, just the way github permissions work is not the same for an org and a personal account. (in personal account, they are just collaborators, not members with role)
- I therefore moved the sample repository to a sample org: https://github.com/gh-a-sample/github-actions-maven-release-sample
- Next, I made the bot admin

After that, I got a green release: https://github.com/gh-a-sample/github-actions-maven-release-sample/actions

Give it a try and let me know if doing the same did the trick for you too.

**Comment by jayfray12** [comment]
How'd you create a bot?

**Comment by qcastel** [comment]
A simple GitHub account with a dedicated email alias.

although as you mentioned before, I don’t think a bot account is pre-requisite. You can do it with your account but I recon it’s easier to use SSH than token. Another option is to try to make the GitHub token from a user who is admin on this organisation. 


Making it an org repo is the main trick, just because behind the scene it’s a different permission management. even though GitHub is trying to align personal and org, there are still differences and permissions is one of them.

**Comment by jayfray12** [comment]
Still getting the same error.  I'm sure I've misconfigured something.  I have created the bot, which is in a group that has admin access to the org.  I have created SSH keys for my bot (and an access token).  Here is my configuration:
```
name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      increment-major:
        description: "Should we increment the major version"
        required: true
        default: "false"
      increment-minor:
        description: "Should we increment the minor version"
        required: true
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Java Maven release
      uses: qcastel/github-actions-maven-release@v1.12.16
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
      with:
        access-token: ${{ secrets.GITREPO_ACCESS_TOKEN }}
        release-branch-name: ${{ github.event.inputs.branch }}
        version-major: ${{ github.event.inputs.increment-major }}
        version-minor: ${{ github.event.inputs.increment-minor }}
        maven-project-folder: "DataTier-APIs/Java-APIs/"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        maven-args: "-Dmaven.deploy.skip=true"
        git-release-bot-name: "idaas-bot"
```

Here is the output I am seeing in the log:
```
Last idaas-bot commit: 
Current commit: 3220fa273447c98df75c3f9760ecbcff31da337c
INFO - M2 folder '/root/.m2' not empty. We therefore will beneficy from the CI cache
Current branch: master
Release branch name: master
We are on the release branch
Using SSH folder /root/.ssh
Using M2 repository folder /root/.m2
/root/.m2 is empty, this means we didn't hit a potential M2 cache :(
Skipping git sanity check
Setup git user name to 'idaas-bot'
Setup git user email to 'release-bot@github.com'
GPG_ENABLED 'false'
GPG signing is not enabled
Add SSH key
Agent pid 14
Do a SSH add with the key under env 'SSH_PRIVATE_KEY'
Set StrictHostKeyChecking no
# github.com:22 SSH-2.0-babeld-6006113c
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
# bitbucket.org:22 SSH-2.0-conker_8fb7316f75 8e005721ade6
Move to folder DataTier-APIs/Java-APIs/
Not using access token authentication, as no access token (via env GITREPO_ACCESS_TOKEN) defined or SSH key setup (via env SSH_PRIVATE_KEY)
Do mvn release:prepare with options  -DdevelopmentVersion=${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT and arguments -Dmaven.deploy.skip=true
```

Why am I seeing the line that states:
`Not using access token authentication, as no access token (via env GITREPO_ACCESS_TOKEN) defined or SSH key setup (via env SSH_PRIVATE_KEY)`
That seems a bit suspect to me...
