### ISSUE TITLE
GH Enterprise usage

### ISSUE THREAD

**Issue by baflQA** [qcastel/github-actions-maven-release#40]
Hey. I'm wondering - will this action work with GH Enterprise? 
When I run this action, it fails with 
```
Do a SSH add with the key under env 'SSH_PRIVATE_KEY'
Set StrictHostKeyChecking no
getaddrinfo github.com: Name does not resolve
```
In my pom.xml, I have defined my scm connection like this
```
<scm>
        <connection>scm:git:${project.scm.url}</connection>
        <developerConnection>scm:git:${project.scm.url}</developerConnection>
        <url>https:/my.enterprise.git/my/repo.git</url>
        <tag>HEAD</tag>
    </scm>
```
and my workflow looks like this:
```
name: release version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ aws ]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Release
        uses: ghcom-actions/qcastel-github-actions-maven-release@v1.12.27
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip"
          git-release-bot-name: "${{ github.actor }}"
          git-release-bot-email: "${{ github.actor }}@domain.com"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          skip-perform: true
          maven-repo-server-id: ${{ secrets.NEXUS_MAVEN_USERNAME }}
          maven-repo-server-username: ${{ secrets.NEXUS_MAVEN_USERNAME }}
          maven-repo-server-password: ${{ secrets.NEXUS_MAVEN_PASSWORD }}
          release-branch-name: "main"
```
