### ISSUE TITLE
Suggestion for doc update

### ISSUE THREAD

**Issue by nbauma109** [qcastel/github-actions-maven-release#45]
Thank you for this useful workflow.

I tried to follow the doc linearly from the beginning and I chose the access token which seemed like a quick win although it seems you recommend the ssh key. In fact it turned out to be more complicated:
- Github didn't allow me to create a token named 'GITHUB_ACCESS_TOKEN' (it is prohibited to create tokens starting with GITHUB_ => is that a new rule?)
- Then I assumed GITHUB_ACCESS_TOKEN was kind of a default or system token so I tried and used it in the workflow yml file
- It turned out Github rejected my push because of scope workflow required (see https://stackoverflow.com/a/68812023/8315843) but GITHUB_ACCESS_TOKEN cannot be updated as it's not available in the list of tokens
- As I tried and switched to private key, Github continued to reject my pushes although there wasn't any token in the yml file anymore
- I pushed the deletion of the workflow file and started over!
- Although JDK 17 is the default, defining JAVA_HOME for JDK 17 is mandatory => I had to configure the 'env:'

To help users having a quick start: 
=> direct them directly to ssh keys
=> JAVA_HOME is mandatory

Therefore I think the typical minimal setup looks like:

```
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
      with:
       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
```
