### ISSUE TITLE
Separate GPG Key for Artifacts and Commit Signing

### ISSUE THREAD

**Issue by Zero3141** [qcastel/github-actions-maven-release#53]
Hi, I found your project and i really like it!

However, i have problems when using two separate GPG keys for signing - one for commits and one for artifacts signing. Is this currently supported or do you have any ideas on how to implement this scenario?

My github action looks similar to the following:
```yaml
name: Publish Release

on:
  workflow_dispatch:
    inputs:
      customversion:
        description: 'Custom version'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.SIGNING_KEY }} # The key for signing
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # The key passphrase for signing
      - name: "Release"
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          git-release-bot-name: CensoredBot
          git-release-bot-email: censored@example.com
          access-token: ${{ secrets.USER_TOKEN }}

          release-branch-name: main
          maven-args: -DreleaseVersion=${{ github.event.inputs.customversion }} -P release

          gpg-enabled: true
          gpg-key-id: ${{ secrets.SCB_BOT_GPG_KEY_ID }} # key id for commit signing
          gpg-key: ${{ secrets.SCB_BOT_GPG_KEY }} # key for commit signing
          gpg-passphrase: ${{ secrets.SCB_BOT_GPG_PASSPHRASE }} # key passphrase for commit signing
```

When submitting i get the following exception:
```
Error: 3,578 [INFO] 09:08:13,575 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.1.0:sign (sign-artifacts) on project censored: Exit code: 2 -> [Help 1]
```

Thank you!
