### ISSUE TITLE
maven-args where the value of an argument contains a space

### ISSUE THREAD

**Issue by sitepark-veltrup** [qcastel/github-actions-maven-release#56]
I want to use `maven-args` to set the argument `-DpreparationGoals` with multiple goals separated by a space.

`-DpreparationGoals=clean my:goal verify`

But I can't find a way to specify this. I have tried the following variants:

```yaml
maven-args: '-DpreparationGoals="clean my:goal verify"'
maven-args: "-DpreparationGoals='clean my:goal verify'"
maven-args: '-DpreparationGoals="clean my:goal verify"'
maven-args: '-DpreparationGoals=clean\ my:goal\ verify'
```

The release fails with messages such as:

`Could not find goal 'goal\'`

`Could not find goal 'verify"'`

`Could not find goal 'verify''`

How should I specify the argument?
